[package]
name = "sztorm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

thiserror = "1.0.38"
speedy = {version = "0.8.3", optional =true}
log = "0.4.17"
rand = "0.8.5"
itertools = "0.10.5"
serde = {version = "1.0.159", optional = true}
ron = {version = "0.8.0", optional = true}
tensorflow = {version="0.20.0", optional = true}

[features]

speedy = ["dep:speedy"]
serde = ["dep:serde"]
simulation = ["dep:serde", "dep:ron", "serde"]
dl = ["dep:tensorflow"]