[package]
name = "tur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

thiserror = "1.0.38"
speedy = {version = "0.8.3", optional =true}
log = "0.4.17"

[features]

serialize_speedy = ["speedy"]
